drop table if exists devut_users cascade;
drop table if exists portfolio_info cascade;
drop table if exists project_info cascade;
drop table if exists project_template cascade;
create table devut_users (
    user_id bigint generated by default as identity,
    login_id varchar(255) not null,
    password varchar(255) not null,
    user_name varchar(255) not null,
    gender enum ('FEMALE','MALE') not null,
    user_div enum ('ADMIN','USER') not null,
    primary key (user_id)
);
create table portfolio_info (
    portfolio_id bigint generated by default as identity,
    user_id bigint unique,
    primary key (portfolio_id)
);
create table project_info (
    project_ended_at date,
    project_started_at date,
    upload_order integer,
    used_yn boolean default true,
    project_info_id bigint generated by default as identity,
    project_template_id bigint not null,
    languages varchar(255),
    project_description varchar(255),
    project_link varchar(255),
    project_title varchar(255),
    primary key (project_info_id)
);
create table project_template (
    portfolio_id bigint unique,
    project_template_id bigint generated by default as identity,
    primary key (project_template_id)
);
alter table if exists portfolio_info
    add constraint FKmfepnmwvq078jdo5v2sfnwd8m
    foreign key (user_id)
    references devut_users;
alter table if exists project_info
    add constraint FKricbk29dth4mgti7c9vcuou9v
    foreign key (project_template_id)
    references project_template;
alter table if exists project_template
    add constraint FKp7gxvj0j9ffbrg561udjloggm
    foreign key (portfolio_id)
    references portfolio_info;